name: Uptime Monitor

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping_site:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Uptime Check
    timeout-minutes: 1   # set timeout to 3 minutes
    steps:
      - name: Debug Cron
        run: |
          echo "Scheduled run at $(date -u) on branch ${{ github.ref }}"
          echo "GitHub Run ID: ${{ github.run_id }}"

      - name: Ping Site
        id: uptime
        uses: srt32/uptime@master
        with:
          url-to-hit: "https://www.megahtex.com/"
          expected-statuses: "200"

      - name: Show Result
        run: |
          echo "Ping step outcome: ${{ steps.uptime.outcome }}"
